### ISSUE TITLE
Invalid handling of numeric bindings in TextBox

### ISSUE THREAD

**Issue by wieslawsoltes** [Perspex/Perspex#487] opened 2016-03-27 12:56 UTC
To reproduce the issue run `BindingTest` sample app and type numbers in Numeric Bindings TextBox:
![2016-03-27_14-48-11](https://cloud.githubusercontent.com/assets/2297442/14065487/d3796b0e-f42b-11e5-81b5-54e44a961636.gif)

**Comment by grokys** [comment] 2016-03-27 20:32
Is the problem here that the value is set to 0 when the `TextBox` is empty?

**Comment by wieslawsoltes** [comment] 2016-03-28 10:56
The issue is when you delete all text and type for example `1` than you get `10` instead of `1`.

**Comment by grokys** [comment] 2016-03-28 12:27
Oh yeah! I've never noticed that. Will fix.

**Comment by jkoritzinsky** [comment] 2016-04-01 18:40
I found the root cause of this bug. When we set the binding value back, we set the value of the backing field to `0`, which then fires `PropertyChanged`, which then causes the converter to convert that `0` back into `'0'` for the text box. For some reason this `'0'` string doesn't show up in the text box, but the value of the `Text` property is `'0'`.

My initial thought is to disable listening when setting the backing value and re-enable it afterwards, but I'm not sure if that's the right way to go. I'll try to prototype a way to do that.

**Comment by grokys** [comment] 2016-04-01 19:09
Yeah, I investigated and found the same. I'm actually about to start working on fixing this :)

I think the solution is to not write `UnsetValue` on binding error - instead we should have something like `Binding.DoNothing`. However this also feeds into a change I wanted to make to make binding errors clearer, so I'm think I will pass a `BindingError` via the observable which will allow logging of which target property the error occurred on etc too.

**Comment by jkoritzinsky** [comment] 2016-04-01 19:15
If we have a `DoNothing`, then what is the backing field set to? I would think that we want it to still set `0` as the value to the property. I'm actually working (almost finished and about to send in the PR) to fix this myself. Just running through some final tests. BTW the binding error is already being logged.

**Comment by grokys** [comment] 2016-04-01 19:18
The backing field will stay at its last valid value, or will get set to `FallbackValue` if that is available - from my tests, this appears to be the way that e.g. WPF binding works.

The binding error is currently logged, but it's not specified in the log what is the target property, right?

Anyway, will be interested to see your PR ;)

**Comment by jkoritzinsky** [comment] 2016-04-01 19:25
PR is #494. Let me know what you think.

**Comment by jkoritzinsky** [comment] 2016-05-02 22:51
@grokys Since this has been fixed, can we close the issue?

**Closed** 2016-05-03 00:06 UTC
